### ISSUE TITLE
Load pre-trained model

### ISSUE THREAD

**Issue by qianzhao0217** [khurramHashmi/FeatEnHancer#15]
![1](https://github.com/user-attachments/assets/9a7cab3f-9d52-4a4f-aaf0-f9c872912fa0)
Hello, this is a very interesting work. I encountered some issues while reproducing the results on the ExDark dataset. I’ve confirmed that the pre-trained model from the COCO dataset is correctly loaded during training on ExDark. However, when running the test_exdark.py file, I couldn’t find any part of the code where the pre-trained model from the ExDark dataset is loaded. It seems that the weights being loaded are still from the COCO pre-trained model. I’m unsure if this is the cause of the discrepancies in the reproduction results.

**Comment by khurramHashmi** [comment]
Hi 
Thanks for your interest.

You have to use [this](https://github.com/khurramHashmi/FeatEnHancer/blob/33da74366d95ebb9b9a94ca85db99ea94f844308/low-light-object-detection-detectron2/test_exdark.sh#L1C1-L1C118) command and give the fine-tuned checkpoint.

**Comment by qianzhao0217** [comment]
Thank you!
