### ISSUE TITLE
more details about the data

### ISSUE THREAD

**Issue by willer94** [khurramHashmi/FeatEnHancer#2]
Hi, the format of the dataset used in this project is different to the original one. Would you please share the annotation files. Thanks a lot !

**Comment by ChengDaTsai** [comment]
> Hi, the format of the dataset used in this project is different to the original one. Would you please share the annotation files. Thanks a lot !

Hi I got same question , have you solved this problem?

**Comment by khurramHashmi** [comment]
Hi,

We follow the same splits as in [MAET](https://github.com/cuiziteng/ICCV_MAET), which were converted into COCO format to benchmark with different methods. Thanks to the authors of MAET, you can find these splits from the following links:
ExDark: [Link](https://drive.google.com/file/d/1X_zB_OSp_thhk9o26y1ZZ-F85UeS0OAC/)
DARK FACE: [Link](https://drive.google.com/file/d/1DuwSRvsYzDpOHdRYG5bk7E45IMDdp5pQ/)

**Comment by Dhs2004** [comment]
> > 您好，本项目使用的数据集格式与原始数据集不同。您能否分享注释文件。多谢！
> 
> 嗨，我有同样的问题，你解决了这个问题吗？

I have the same problem, can you please solve it


> > 您好，本项目使用的数据集格式与原始数据集不同。您能否分享注释文件。多谢！
> 
> 嗨，我有同样的问题，你解决了这个问题吗？

I have the same problem, can you please solve it
