### ISSUE TITLE
"self.scale_aware_aggregation = ScaleAwareFeatureAggregation(channels=32).to('cuda')"

### ISSUE THREAD

**Issue by Felix-fz** [khurramHashmi/FeatEnHancer#3]
Hi,
    Thanks for your insteresting work! But when I run the "FeatEnHancer", the "channels" of"self.scale_aware_aggregation = ScaleAwareFeatureAggregation(channels=32).to('cuda')"  is wrong? Because the "out_channels=32". And the result of "self.quarter_conv" is [B, int_out_channels, H/4-1,W/4-1]?
![image](https://github.com/khurramHashmi/FeatEnHancer/assets/61495551/c926f876-79f5-4bc9-9e51-3518843b07f7)
Best wishes!

**Comment by khurramHashmi** [comment]
Hi,

Thanks for your interest in our work, and apologies for the late response.

No, ``channels=32`` in ScaleAwareFeatureAggregation (SAFA) is not wrong. ``Self.quarter_conv`` is used to simply downscale the input image and its output is not used in SAFA. Instead, the output from later convolutional layers is used in SAFA.

**Comment by khurramHashmi** [comment]
Hi,

Thank you for your interest in our work, and apologies for the late response.

The `self.quarter_conv` is used to downscale the input image, and its output is not utilized in ScaleAwareFeatureAggregation (SAFA). However, you are correct that there is a mismatch with `channels=32` in SAFA, which should be `channels=24`. This has now been resolved. Thank you for bringing this up.

**Comment by stephenwang0317** [comment]
Hey, I encountered the same issue, but mine is not about the number of channels—it’s about the feature map ***size*** after convolution.

In the **quarter_conv layer**, based on the convolution formula, when the input height (H) and width (W) are both $$X$$, with a stride of 7 and a kernel size of 4, the expected output size should be $$(\frac{X}{4}-1, \frac{X}{4}-1)$$. It does not follow the expected 1/4 scaling relationship.

Should ***padding*** be added to correct the feature map size? Or is there another intended behavior for quarter_conv?

Looking forward to your response. Thanks!
