### ISSUE TITLE
about datasets

### ISSUE THREAD

**Issue by MidsummerHi** [khurramHashmi/FeatEnHancer#5]
Hi,bro,how can i get the train sets and tests sets?i dont know the right sets image list.can you provide the train and test sets json file? or the datasets splits image list.
thank you!

**Comment by MidsummerHi** [comment]
> Hello,
> 
> This has already been discussed here: [#2 (comment)](https://github.com/khurramHashmi/FeatEnHancer/issues/2#issuecomment-2242589960)

thank you，I got it. but there is no json file about splits.

according to your code,I found It need two json file, I can convert on my own,but I wanna know the json file's format first.
 
 thank you

**Comment by khurramHashmi** [comment]
It should be a standard COCO format.

**Comment by MidsummerHi** [comment]
> It should be a standard COCO format.
